# 1. Dependencias
FROM node:22-alpine AS deps

WORKDIR /app

COPY package*.json ./
RUN npm install

# 2. Build
FROM node:22-alpine AS build

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

# 3. Producción
FROM node:22-alpine AS prod

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

#4 Uploads
RUN mkdir -p uploads

ENV NODE_ENV=production

EXPOSE 3005

CMD ["node", "dist/main.js"]